config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'lists/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, presence: true
  validates :list, presence: true
  validates :comment, length: { maximum: 500 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  accepts_nested_attributes_for :bookmarks, allow_destroy: true, reject_if: :all_blank
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@list), notice: 'Movie was successfully added to the list.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully deleted.'
  end

  private

  # def bookmark_params
  #   params.require(:bookmark).permit(:movie_id, :comment)
  # end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.includes(bookmarks: :movie).all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
    @list.bookmarks.build
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list), notice: 'List was successfully updated.'
    else
      render :edit
    end
  end
  

  def destroy
    @list = List.find(params[:id])
    @list.bookmarks.destroy_all
    @list.destroy
    redirect_to lists_path, notice: 'List and associated bookmarks were successfully deleted.'
  end

  private

  def set_list
    @list = List.find(params[:id])
  end


  def list_params
    params.require(:list).permit(:name, bookmarks_attributes: [:id, :movie_id, :comment, :_destroy])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    url = "https://api.themoviedb.org/3/movie/popular?api_key=#{TMDB_API_KEY}"
    response = HTTParty.get(url)
    if response.code == 200
      @movies = JSON.parse(response.body)['results']
      puts "Movies: #{@movies.inspect}"
    else
      flash[:alert] = 'Failed to fetch movies from the API.'
      @movies = []
    end
  end
end
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/bookmarks/new.html.erb
<h1>Add Movie to List</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, prompt: 'Select a movie' %>
  <%= f.input :comment, label: 'Comment', input_html: { rows: 3 } %>
  <%= f.button :submit, 'Add Movie' %>
<% end %>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1 class="mb-4">Add a movie to <%= @list.name %></h1>

<%= form_with(model: [@list, @bookmark], local: true, html: { class: 'form-group' }) do |form| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
      <ul>
        <% @bookmark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :movie_id %>
    <%= form.collection_select :movie_id, Movie.all, :id, :title, { prompt: 'Select a movie' }, { class: 'form-control' } %>
  </div>

  <div class="field form-group">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Add Movie', class: 'btn btn-primary mt-3' %>
  </div>
<% end %>

<%= link_to 'Back', list_path(@list), class: 'btn btn-secondary mt-3' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watch List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to 'All Movies', movies_index_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'My Lists', lists_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'New List', new_list_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_bookmark_fields.html.erb
<div class="nested-fields">
  <%= f.association :movie, prompt: 'Select a movie' %>
  <%= f.input :comment, label: 'Comment', input_html: { rows: 3 } %>
  <%= link_to 'Remove Movie', '#', class: 'remove_bookmark_fields btn btn-danger', data: { action: 'click->bookmarks#removeFields' } %>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.association :movie, collection: Movie.all, prompt: 'Select a movie' %>
  <%= f.button :submit %>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>

  <div id="bookmarks">
    <%= f.simple_fields_for :bookmarks do |bookmark_form| %>
      <%= render 'bookmark_fields', f: bookmark_form %>
    <% end %>
  </div>

  <%= link_to 'Add Movie', '#', class: 'add_bookmark_fields btn btn-success' %>

  <%= f.button :submit, 'Update List' %>
<% end %>

app/views/lists/index.html.erb
<h1>My Lists</h1>

<%= link_to 'Create a New List', new_list_path, class: 'btn btn-success mb-3' %>

<% @lists.each do |list| %>
  <div class="list-container mb-3">
    <h2><%= link_to list.name, list_path(list) %></h2>
    <%# <%= link_to 'Edit', edit_list_path(list), class: 'btn btn-primary' %>
    <%= link_to 'Delete', list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> |
    <%= link_to 'View Movies', list_path(list), class: 'btn btn-secondary' %> 
  </div>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>

  <%= f.simple_fields_for :bookmarks, @bookmark do |bookmark_form| %>
    <%= bookmark_form.association :movie, prompt: 'Select a movie' %>
    <%= bookmark_form.input :comment, label: 'Comment', input_html: { rows: 3 } %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<% @list.bookmarks.each do |bookmark| %>
  <div class="list-container mb-3">
    <h2><%= bookmark.movie.title %></h2>
    <p><%= bookmark.movie.overview %></p>
    <p>Comment: <%= bookmark.comment %></p>
  </div>
<% end %>

<div class="d-flex button-container">
  <%= link_to 'Add Movie', new_list_bookmark_path(@list), class: 'btn btn-success mr-2' %> |
  <%# <%= link_to 'Edit', edit_list_path(@list), class: 'btn btn-primary mr-2' %>
  <%= link_to 'Back', lists_path, class: 'btn btn-secondary mr-2' %> |
  <%= button_to 'Delete List', list_path(@list), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>

app/views/movies/index.html.erb
<div class="container">
  <h1 class="text-center my-4">All Movies</h1>
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-md-6 mb-4">
        <div class="card">
          <%= image_tag "https://image.tmdb.org/t/p/w500#{movie['poster_path']}", class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title"><%= movie['title'] %></h5>
            <p class="card-text"><%= movie['overview'] %></p>
            <p class="card-text">Rating: <%= movie['vote_average'] %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>